services:
  - type: web
    name: ptu-grade-portal
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn Result:app --host 0.0.0.0 --port $PORT --app-dir backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: REFRESH_SECRET_KEY
        generateValue: true
      - key: REPORT_CARD_TOKEN_SECRET
        generateValue: true
